apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: cluster-ocp-48-k
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/cluster-ocp-48-k.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true