apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJtaXJyb3ItcmVnaXN0cnktdnJhbm1nbXQxLmZ5cmUuaWJtLmNvbTo1MDAwIjp7InVzZXJuYW1lIjoiaWJtdXNlciIsInBhc3N3b3JkIjoiaWJtcGFzc3dvcmQiLCJhdXRoIjoiYVdKdGRYTmxjanBwWW0xd1lYTnpkMjl5WkE9PSIsImVtYWlsIjoidmlqamF5MTJAaW4uaWJtLmNvbSJ9fX0=
kind: Secret
metadata:
  labels:
    agentclusterinstalls.extensions.hive.openshift.io: "true"
  name: assisted-deployment-pull-secret
  namespace: ocp-48-cluster-k
type: kubernetes.io/dockerconfigjson
