apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sm-101-feb14"
  namespace: "sm-101-feb14"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-sm-101-feb7" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDanPfezUPy2ddKbpWSozdsL+Z6gbY6vCfWFe/wKcw+nF5qGMCcdZ1CH/chxhB2rlvXikhewl5XXQJ6cow5hJw7yJ5Md+W99dfvSeDrN+DrJ4NhWqsN9IF7JhpF3KlfWe8Hgw1r9+xbfpVeadtTABhBZAOwgTtZjDkDqBKlz62eG9S4JoBmlIfc5s012eCY5e0kFKv6eGfyg170/zfDLCdSU1BAawnwq6IJ0pFxDoyESTi9ysboahoaxa8ZLnDyvLAX5U/H0ciWJ2WIYdU/GFx/ys6sVazZ+q9EReKUkGTGyoQ6jtwTzlQU4gxPqjUsy9IgmZNEFbOR9Az0DRnGgsFB"
  clusters:
  - clusterName: "sm-101-feb14"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "sm-101-feb14"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    additionalNTPSources:
       - 9.37.131.200
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "sm-101-feb14"
         bmcAddress: "redfish-virtualmedia+https://9.37.131.101/redfish/v1/Systems/1" 
         bmcCredentialsName:
           name: "sm-101-feb14-sm-101-feb14-bmh-secret"
         bootMACAddress: "3C:EC:EF:5E:BC:28"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "3C:EC:EF:5E:BC:28"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "3C:EC:EF:5E:BC:28"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
