apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sm-101-feb14"
  namespace: "sm-101-feb14"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-sm-101-feb7" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtSSAdscOA8tSayvbyZ06W2VhBleikMpWoXNAzRFJhvul0qZ0AGM3Cm6F/E8IuObV34iepBkhRdAw/zgBfMJiyADOj2V6UmxVXi5OVD4qqoMa1qngahJjls3wy6+0WYXvu4fSHLuPIpGnVUIPB8fWQIy9HjFjTJ/FZLrEDaieEd0j2KvL3mmYtGCFX8Jh4+wxSIhkqjv/qPsbH1ypTUvjxA7LDJbp/e0GtO/qfEYQKFiNnJ+fm0c5oV4o8H6M9fJd13+SAHKwnhjVDNdyhggSzsyG1ZV/vGi8Gs7Tf7wIekqv2+nLTfSk+aL6XFg2lGzap5VD5QzO1AGSX2XLcevrb"
  clusters:
  - clusterName: "sm-101-feb14"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "sm-101-feb14"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    additionalNTPSources:
       - 9.37.131.200
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "sm-101-feb14"
         bmcAddress: "redfish-virtualmedia+https://9.37.131.101/redfish/v1/Systems/1" 
         bmcCredentialsName:
           name: "sm-101-feb14-sm-101-feb14-bmh-secret"
         bootMACAddress: "3C:EC:EF:5E:BC:28"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "3C:EC:EF:5E:BC:28"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "3C:EC:EF:5E:BC:28"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
