apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sm-101-feb24.vran.ibm.com-gitops
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: clusters/sm-101-feb24.vran.ibm.com/ztp/gitops
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
