apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: ocp48-cluster-k
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/ocp48-cluster-k.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true