apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-48-cluster-k.vran.ibm.com-gitops
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: telco-gitops/clusters/ocp-48-cluster-k.vran.ibm.com/ztp/gitops
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true