apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "dell-44"
  namespace: "dell-44"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-sm-101-feb7" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzeFq7hj9Ci9/HTpSMCiey7SipTmplVx+ckcrdoMnr4fEvx/wL59LXZLN7z5eySwh1u3j9Cmi7J8eZ/Lnr9WElNoW9g9a7f8fiffZlKkT71FGQq2CFgcPzjt8dQGSoVwt/XjH7MrsJsFzT3M7cNFd4VJydWY72H9i8eqAaOAJOGJ3lnXnxiZiwUgryYQsg8UG5RbF35iKF2xHriPdP7b+b51mTH9bqDuEJOLqhm1J17lC5LgrDQpeC5GDpJNw8pI5HZL8v1P7ZVvx5dRXoZ+cmsCgcGC90If+Bhpn6nUWCCq5Qh5mX1Zb7EEDyrvKk3oZpm4wieGjY/NSYXRFrz0DL"
  clusters:
  - clusterName: "dell-44"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "dell-44"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    additionalNTPSources:
       - 9.37.131.200
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "dell-44.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "dell-44-dell-44-bmh-secret"
         bootMACAddress: "78:AC:44:22:9B:74"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:9B:74"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:9B:74"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
