---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster01
  namespace: cluster01
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: cluster01
    version: v1beta1
  clusterName: cluster01
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: cluster01
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: cluster01
  namespace: cluster01
spec:
  apiVIP: 9.37.195.12
  ingressVIP: 9.37.195.15
  clusterDeploymentRef:
    name: cluster01
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
    workerAgents: 2
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-1"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcxiYc4jgW4HOhwkZIMS8MgSsrle5bnbqXIMjGvV090MsF/UtiEfuD/7mrnf8D1mG4xzidrUhzTj8Zp2LVOXaC+pUtHsf91WUFsvBpajBPgXqQmnKu06DLay2ciw8z+yjeN36ynbxpdb633wOF2TyeGTmeLhpnAaSbCdsCxBBgLHVc5THVQYPJpOxhr8HKWvrDBhHXhT3RllZd3mHb3CmffVdY5L7OyShRRfDnl/Z3vojf2XQy6SsCmHSihFjprQk+ZSILH6UzQLvsQvbUONlImBkWrwE9iZHKhaneajT5zRMdNyE8r1/7iZ0JDWEpLm08lzQAf/U1UWoufCqjYRoGfTe3KI/flW3nc3EbR1b5MtMsZ2HCPHfwRjkSP2pgcFVAyDru6ANTBPvxsdfkvspM1+bgsZuk/GTUzZsKPi7P2uqONoV3OgcauzfI4nrM1XeGNOCuUuvCirrTq9wfdKuQePu8nP4wYqcrw08UE+nGxUEX4WlCL6nmzu7HNGQlNU8= root@provisioner1.fyre.ibm.com"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster01
  namespace: cluster01
spec:
  clusterName: cluster01
  clusterNamespace: cluster01
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: cluster01
  namespace: cluster01
  
spec:
  clusterRef:
    name: cluster01
    namespace: cluster01
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: cluster01
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcxiYc4jgW4HOhwkZIMS8MgSsrle5bnbqXIMjGvV090MsF/UtiEfuD/7mrnf8D1mG4xzidrUhzTj8Zp2LVOXaC+pUtHsf91WUFsvBpajBPgXqQmnKu06DLay2ciw8z+yjeN36ynbxpdb633wOF2TyeGTmeLhpnAaSbCdsCxBBgLHVc5THVQYPJpOxhr8HKWvrDBhHXhT3RllZd3mHb3CmffVdY5L7OyShRRfDnl/Z3vojf2XQy6SsCmHSihFjprQk+ZSILH6UzQLvsQvbUONlImBkWrwE9iZHKhaneajT5zRMdNyE8r1/7iZ0JDWEpLm08lzQAf/U1UWoufCqjYRoGfTe3KI/flW3nc3EbR1b5MtMsZ2HCPHfwRjkSP2pgcFVAyDru6ANTBPvxsdfkvspM1+bgsZuk/GTUzZsKPi7P2uqONoV3OgcauzfI4nrM1XeGNOCuUuvCirrTq9wfdKuQePu8nP4wYqcrw08UE+nGxUEX4WlCL6nmzu7HNGQlNU8= root@provisioner1.fyre.ibm.com"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-44-01"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-44-01-bmh-secret
  bootMACAddress: 78:AC:44:22:9B:74
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-45-01"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.45/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-45-01-bmh-secret
  bootMACAddress: 78:AC:44:22:99:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-68-01"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.68/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-68-01-bmh-secret
  bootMACAddress: 78:AC:44:32:91:20
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-72-01"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.72/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-72-01-bmh-secret
  bootMACAddress: 78:AC:44:32:7D:D0
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-73-01"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.73/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-73-01-bmh-secret
  bootMACAddress: 78:AC:44:32:7A:D0
  automatedCleaningMode: disabled
  online: true
---
