apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: telco-gitops/clusters/ocp-48-cluster-k.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/Sin317/ztp-manifests.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true