apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-ocp-48-k-siteconfig
  project: default
  source:
    path: clusters/cluster-ocp-48-k.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/Sin317/telco-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
